### ISSUE TITLE
PV object is getting deleted but actual volume still present from IaaS

### ISSUE THREAD

**Issue by arahamad** [kubernetes-sigs/ibm-vpc-block-csi-driver#126]
This is the case when volume deletion stuck from IaaS and CSI driver is deleting PV object, this will left the volume as it is from IaaS.

**Comment by subhashmk** [comment]
@arahamad Can you please share some more details, like when this happens, so that we can try to reproduce and fix it?

**Comment by madhulika2709** [comment]
@arahamad can you add more details on this issue for @subhashmk to take it further

**Comment by subhashmk** [comment]
@arahamad Could you please assign this issue to myself.
