### ISSUE TITLE
 Identify how PVC variable can be parametrised specially for iops, zone and KP etc

### ISSUE THREAD

**Issue by arahamad** [kubernetes-sigs/ibm-vpc-block-csi-driver#129]

**Comment by sreee9** [comment]
Madhu and I will be working on this issue.

**Comment by sameshai** [comment]
Some of the initial analysis I had done discussion with k8s community 

 Identify how PVC variable can be parametrised specially for iops, zone and KP etc.

We have analysed different ways but the only possible way to pass zone is storage class , pod affinity and PVC annotations.

For Iops the only possible way is storage class.

```
Zones should be specified as part of a Pod via its affinity / anti affinity. The volume gets then provisioned in the right zone that has both enough storage available and satisfies pod needs.

For the other parameters, StorageClass is currently the only way. It intentional, we do not want to "leak" storage details into PVCs. Such PVCs would not be portable to a different storage system, with say different annotations.
```

Slack discussion with Kubernetes community @jsafrane

https://kubernetes.slack.com/archives/C09QZFCE5/p1632203456111900

**Comment by madhulika2709** [comment]
@sameshai we have analysed from our side and the conversations above.  only way is storage class. if we use the storage class, those details will be exposed right. shall we go ahead with changes for this or any other suggestions on this. please let us know

**Comment by madhulika2709** [comment]
@sameshai As discussed earlier, we could not find any other way to go ahead with this except for storage class and because of the downsides of storage class, we cannot take this further. please let me know if any more discussions have been on this or we can go ahead with next issue
