### ISSUE TITLE
create deployment object for ibm-vpc-block-csi-driver instead of StatefulSets

### ISSUE THREAD

**Issue by arahamad** [kubernetes-sigs/ibm-vpc-block-csi-driver#130]

**Comment by subhashmk** [comment]
@arahamad can you please assign this to myself. I'll look into this issue.

Also, could you please add some more details?

**Comment by subhashmk** [comment]
@arahamad I am not able to create branch as well on this repo.

**Comment by arahamad** [comment]
@subhashmk , you can fork it and raise PR

**Comment by subhashmk** [comment]
I think, this issue is already taken care by PR kubernetes-sigs/ibm-vpc-block-csi-driver#134. Therefore this issue can be closed.
