### ISSUE TITLE
Identifying and updating right version of sidecars for all overlays

### ISSUE THREAD

**Issue by arahamad** [kubernetes-sigs/ibm-vpc-block-csi-driver#132]
Identifying and updating right version of sidecars and driver version for all overlays https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/tree/master/deploy/kubernetes/driver/kubernetes/overlays

**Comment by Sony-Neyyan** [comment]
Hi @arahamad
Can you please assign this issue to me (id: https://github.com/Sony-Neyyan)
