### ISSUE TITLE
vendorVersion is not getting updated in the log

### ISSUE THREAD

**Issue by arahamad** [kubernetes-sigs/ibm-vpc-block-csi-driver#133]
https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/blob/master/cmd/main.go#LL87C69-L87C82 i snot working as expected

**Comment by Sony-Neyyan** [comment]
Hi @arahamad 
Can you please assign this issue to me (id: https://github.com/Sony-Neyyan)
