### ISSUE TITLE
Enable gosec check

### ISSUE THREAD

**Issue by prankulmahajan** [kubernetes-sigs/ibm-vpc-block-csi-driver#152]
As of now we are doing following verify tests. https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/blob/master/hack/verify-all.sh

We need to add gosec to this list.

**Comment by nishubharti** [comment]
i am looking into this issue

**Comment by nishubharti** [comment]
i have raised pr here https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/pull/163 
@prankulmahajan can you please review it once
