### ISSUE TITLE
Validate README steps and fix scripts

### ISSUE THREAD

**Issue by ambiknai** [kubernetes-sigs/ibm-vpc-block-csi-driver#154]
Starting from [Prereq](https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver#prerequisites) to [Deleting the driver](https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver#delete-csi-driver-from-your-cluster), One has to go through README and try out each step .

For any broken steps, work on the fix and raise a PR with sufficient test results.

Test on all possible platforms from which user can try installing this driver

**Comment by madhulika2709** [comment]
@ambiknai can you add more details on this task

**Comment by subha-91** [comment]
@arahamad Can you please assign the issue
