### ISSUE TITLE
Resize filesystem of a larger volume created from a snapshot/volume

### ISSUE THREAD

**Issue by RomanBednar** [kubernetes-sigs/ibm-vpc-block-csi-driver#85]
Upstream [issue](https://github.com/kubernetes/kubernetes/issues/94929) introduces improvements to volume resizing. The change added new resize code and moved to [kubernetes/mount-utils](https://github.com/kubernetes/mount-utils). 

This change should be reflected in all CSI drivers. New module should be imported and it's resize logic added. 

Dependency should be updated to use the current k8s/mount-utils module and CSI driver should use the resize code it provides in NodeStageVolume to perform the resize if needed. Example of similar change can be found [here](https://github.com/kubernetes/cloud-provider-openstack/pull/1563/files)

Issue originated in [BZ1877261](https://bugzilla.redhat.com/show_bug.cgi?id=1877261)

#### How to reproduce:
1. create original pod and pvc
2. create snapshot from original pvc
3. create pvc from the snapshot specifying larger size than the original
4. create pod to consume the new pvc
5. observe fs size of the new volume inside the pod does not match the requested size

**Comment by arahamad** [comment]
Thank you @RomanBednar, will plan to fix

**Comment by ambiknai** [comment]
@RomanBednar 
Please could you explain how this step is executed
```
create snapshot from original pvc
```
Right now the code base in this repo doesn't support snapshot feature from driver.

**Comment by RomanBednar** [comment]
I see...it's strange however because [docs](https://cloud.ibm.com/docs/containers?topic=containers-vpc-volume-snapshot#vpc-create-snapshot) mention volume snapshots and apparently the IBM Kubernetes service is using the same driver as this one because the driver name [(vpc.block.csi.ibm.io)](https://cloud.ibm.com/docs/containers?topic=containers-vpc-block#vpc-block-static) in the doc [matches](https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/blob/a4637532095c1dd4976bfba561cb8169174628aa/deploy/kubernetes/driver/kubernetes/manifests/csidriver.yaml#L4). 

Checking the e2e tests in openshift for ibm driver shows that we don't even [test snapshots](https://github.com/openshift/ibm-vpc-block-csi-driver-operator/blob/master/test/e2e/manifest.yaml#L23).

@ambiknai Can we then assume that snapshots are not supported with ibm driver? If so please close the issue as it's not relevant.

**Comment by RomanBednar** [comment]
Thank you for the update @arahamad. That means the snapshot resize issue is relevant again. I've looked at the code and this is not a trivial change. Please take a look at my PR and review: https://github.com/kubernetes-sigs/ibm-vpc-block-csi-driver/pull/100

Second thing that popped up are the problematic sanity tests, I've linked that in the PR as well - you should find all important links there. For more context: [here](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/972#issuecomment-1130221537) is where I've encountered the issue initially when fixing GCP driver.
